type User @table {
  displayName: String!
  email: String
  photoUrl: String
  createdAt: Timestamp!
}

type Movie @table {
  title: String!
  releaseYear: Int!
  summary: String
  genres: [String]
  runtime: Int
  posterUrl: String
  createdAt: Timestamp!
}

type Watch @table {
  user: User!
  movie: Movie!
  watchDate: Date!
  location: String
  createdAt: Timestamp!
}

type Review @table {
  watch: Watch!
  rating: Int!
  text: String
  isPublic: Boolean
  createdAt: Timestamp!
  updatedAt: Timestamp!
}